# Use Alpine Linux as the base image
FROM alpine:latest

# Install necessary packages
RUN apk add --no-cache \
	openssh-server \
	openssh-sftp-server \
	mariadb-client \
	linux-pam \
	openssh-server-pam \
	bash

# Create a user for SFTP access
RUN addgroup -g 991 asterisk && \
	adduser -D -u 990 -h /var/sftp -s /sbin/nologin -G asterisk asterisk && \
	mkdir -p /var/sftp && \
	chown root:root /var/sftp && \
	chmod 755 /var/sftp

# Copy configuration files
COPY sshd_config /etc/ssh/sshd_config
COPY pam_config /etc/pam.d/sshd
COPY check_mysql_password.sh /usr/local/bin/check_mysql_password.sh
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
